// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTvF0DiUxjoUzfBIyimVh5Fua05BPJmZk',
    appId: '1:721653983645:web:532fcec2c943ae820c6774',
    messagingSenderId: '721653983645',
    projectId: 'safestreets-7f994',
    authDomain: 'safestreets-7f994.firebaseapp.com',
    storageBucket: 'safestreets-7f994.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_-MG_TwsK1E0rZqEY24BTXZwv1vgfr6o',
    appId: '1:721653983645:android:7e161de10ebb9d500c6774',
    messagingSenderId: '721653983645',
    projectId: 'safestreets-7f994',
    storageBucket: 'safestreets-7f994.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSzvrlojWLf8_aSwNTCiJnmTvdRTD8GIw',
    appId: '1:721653983645:ios:91894abebe8edd290c6774',
    messagingSenderId: '721653983645',
    projectId: 'safestreets-7f994',
    storageBucket: 'safestreets-7f994.appspot.com',
    iosClientId:
        '721653983645-582ttjthr7c48o5pb80mb5u741j0qhum.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeStreets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSzvrlojWLf8_aSwNTCiJnmTvdRTD8GIw',
    appId: '1:721653983645:ios:91894abebe8edd290c6774',
    messagingSenderId: '721653983645',
    projectId: 'safestreets-7f994',
    storageBucket: 'safestreets-7f994.appspot.com',
    iosClientId:
        '721653983645-582ttjthr7c48o5pb80mb5u741j0qhum.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeStreets',
  );
}
