# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x08SafeCity\"2\n\x0fGenericResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"V\n\x04User\x12\n\n\x02id\x18\x01 \x01(\r\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x14\n\x07\x63ity_id\x18\x04 \x01(\x05H\x00\x88\x01\x01\x42\n\n\x08_city_id\"c\n\x08\x42\x61\x64Place\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07user_id\x18\x02 \x01(\r\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0c\n\x04long\x18\x04 \x01(\x01\x12\x0f\n\x07\x63omment\x18\x05 \x01(\t\x12\x0e\n\x06rating\x18\x06 \x01(\r\"\x07\n\x05\x45mpty\")\n\x08UserList\x12\x1d\n\x05users\x18\x01 \x03(\x0b\x32\x0e.SafeCity.User\"5\n\x0c\x42\x61\x64PlaceList\x12%\n\tBadPlaces\x18\x01 \x03(\x0b\x32\x12.SafeCity.BadPlace2\xbe\x03\n\x0fSafeCityService\x12\x36\n\x07\x41\x64\x64User\x12\x0e.SafeCity.User\x1a\x19.SafeCity.GenericResponse\"\x00\x12\x39\n\nUpdateUser\x12\x0e.SafeCity.User\x1a\x19.SafeCity.GenericResponse\"\x00\x12\x34\n\x0bGetAllUsers\x12\x0f.SafeCity.Empty\x1a\x12.SafeCity.UserList\"\x00\x12>\n\x0b\x41\x64\x64\x42\x61\x64Place\x12\x12.SafeCity.BadPlace\x1a\x19.SafeCity.GenericResponse\"\x00\x12\x41\n\x0eUpdateBadPlace\x12\x12.SafeCity.BadPlace\x1a\x19.SafeCity.GenericResponse\"\x00\x12\x41\n\x0e\x44\x65leteBadPlace\x12\x12.SafeCity.BadPlace\x1a\x19.SafeCity.GenericResponse\"\x00\x12<\n\x0fGetAllBadPlaces\x12\x0f.SafeCity.Empty\x1a\x16.SafeCity.BadPlaceList\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERICRESPONSE._serialized_start=27
  _GENERICRESPONSE._serialized_end=77
  _USER._serialized_start=79
  _USER._serialized_end=165
  _BADPLACE._serialized_start=167
  _BADPLACE._serialized_end=266
  _EMPTY._serialized_start=268
  _EMPTY._serialized_end=275
  _USERLIST._serialized_start=277
  _USERLIST._serialized_end=318
  _BADPLACELIST._serialized_start=320
  _BADPLACELIST._serialized_end=373
  _SAFECITYSERVICE._serialized_start=376
  _SAFECITYSERVICE._serialized_end=822
# @@protoc_insertion_point(module_scope)
