DROP TABLE IF EXISTS users, places, votes;
CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firebase_user_id" varchar(255) unique,
  "full_name" varchar,
  "email" varchar unique,
  "created_at" timestamp DEFAULT (now()),
  "city_id" int
);

CREATE TABLE "places" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firebase_user_id" varchar(255),
  "title" varchar(255),
  "main_type" varchar,
  "sub_type" varchar,
  "comment" varchar,
  "lat" numeric(20,15),
  "long" numeric(20,15),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "votes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firebase_user_id" varchar(255),
  "place_id" int,
  "vote" int,
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "users" ("firebase_user_id");

CREATE INDEX ON "places" ("firebase_user_id");

CREATE INDEX ON "votes" ("firebase_user_id");

CREATE INDEX ON "votes" ("place_id");

ALTER TABLE "places" ADD FOREIGN KEY ("firebase_user_id") REFERENCES "users" ("firebase_user_id");

ALTER TABLE "votes" ADD FOREIGN KEY ("firebase_user_id") REFERENCES "users" ("firebase_user_id");

ALTER TABLE "votes" ADD FOREIGN KEY ("place_id") REFERENCES "places" ("id");
